[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = [
    "homeassistant",
]
split-on-trailing-comma = false
