name: Validate for HACS

on:
  merge_group:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  hacs:
    name: 
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hacs/action@dcb30e72781db3f207d5236b861172774ab0b485" # main
        with:
          category: "integration"
