name: Validate with hassfest

on:
  merge_group:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7
        with:
          persist-credentials: false
      - uses: "home-assistant/actions/hassfest@58bff37c8947f690ace498be413a9b78d6f30f93" # master

