name: Validate with hassfest

on:
  merge_group:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7
        with:
          persist-credentials: false
      - uses: "home-assistant/actions/hassfest@f4ca6f671bd429efb108c0f2fa0ae8af0215986c" # master

